plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: minima

header_pages:
  - README.md
  - 00.%20journal/01.%20logs/journal_1_logs.html
