#+TITLE: Science 1 Logs

#+BEGIN_EXPORT html
<pre>
<code>> ./blog-1/02_science/01_logs/science_1_logs.html</code>
</pre>
#+END_EXPORT

[[https://hnvy.github.io/blog-1/][Home page]] - [[https://github.com/hnvy/blog-1/edit/main/src/02_science/01_logs/science_1_logs.org][ESotP]]

-----

* Introduction
:PROPERTIES:
:CUSTOM_ID: intro
:END:
See [[http://hnvy.github.io//about.html#science][this]].

* Disclaimer: this document is NOT for medical advice
:PROPERTIES:
:CUSTOM_ID: org270729d
:END:
@@html:<p><span style="text-decoration: underline; background-color: yellow; color: red;"><strong>Please note that the following content is not intended to be used as a diagnostic or treatment tool. If you are having any symptoms, you should always seek medical advice. My notes are not intended to be medical advice; you should seek guidance from your physician rather than the internet. Once again, this document is NOT for medical advice!</strong></span></p>@@

* E#014 (14/11/2022) - coal (A)
:PROPERTIES:
:CUSTOM_ID: org1632067
:END:
Expressed!
[[https://lh3.googleusercontent.com/pw/AL9nZEXY-8hB_xSGbZe6jpW4zbDqbzubO06YeEYOL2pAuaH-D-gDZEYID6oB3QnMnq7mFV690GONQs0SuXU95L077G4pV25EbTWa4Toj0bmra00i3teBkBsg8PjYr9mwIgEnd3rUD9O3gSGaEaFXjbBr2Xk=s500-no?authuser=0][Here is the picture]]

* E#013 (25/06/2022) - dragon's heart (A)
:PROPERTIES:
:CUSTOM_ID: org1oplxms
:END:
The animal is constructed from the materials found in its heart. By extension, a dragon has a heart that is designed like a dragon. The anatomists have yet to witness this as of this writing. In light of this, I wonder what it means to "possess lionheart."

[[https://lh3.googleusercontent.com/pw/AL9nZEWmlURuTfBqHs_UKMr0JnkJGbkJspwL8i2kehIEpFoi02FfwIICa5_x6mOWg8hIhAt-ey2_tvoeWsdCEiwBsHAbviJEPEuM5jLD1ehXrS-Rd8d5TAr-6QYo_6YxxG-XEs1izWMNd3nV0Ns0jmX91mU=s500-no?authuser=0][Here is the picture]]

* E#012 (12/05/2022) - bus stop (A)
:PROPERTIES:
:CUSTOM_ID: org20ca0ad
:END:
The bus stop is probably one of the most tranquil places for the girl to play the ney in order to summon earthworms from the ground, which would create tunnels providing air circulation and allowing the ants to build houses, rooms, shops, and tools.

[[https://lh3.googleusercontent.com/pw/AM-JKLWJWl35vH1vA23CDlwqtmwHr98-lcp4IOMdpgg6Smt4Kftk4yLXRDUXbJGIemywlrmqHiLAvM3jelG1qApOLN7EfZzvYTEQ9nY4LpE5zAIsSrLcZKtzqnutoIZOqk440pCfSXgKLSbuHYLEp6qa0jY=s500-no?authuser=0][Here is the picture]]

* E#011 (08/05/2022) - tree man (A)
:PROPERTIES:
:CUSTOM_ID: org6b910de
:END:
The man who opposes technology sits alone, his head against a tree, along the road/river (depending on how you look at it), simply reminiscing in a land where technology is widely utilised and required. Meanwhile, in the background, the sky is covered with constructions that block out all natural night light and replace it with dazzling artificial light. What shall he do? Accept it? Or continue to oppose?

[[https://lh3.googleusercontent.com/pw/AM-JKLXmupsfkNCBltdgIrw2RiuEeNdESroz748o86zf7lfZyykFEJFDmsng-0_c_QWUKYhepMO3x2BBYPztMna9lg-qwbJKSeSjaLn8CMcEgW5mL9osjmN9CQDyKvxfVzD_NrBwVvpFcTcuFIXGOyI_x08=s500-no?authuser=0][Here is the picture]]

* E#010 (07/05/2022) - shadows (A)
:PROPERTIES:
:CUSTOM_ID: org2c6c7ed
:END:
A human emerges from the shadows. An oppressed individual. A hopeful human. A person who recognises their true essence.

[[https://lh3.googleusercontent.com/pw/AM-JKLWrM2Mt6igPfJV6_98SOmugmry104JuVTLm18mwnxN7UPJlIUIPOtMqkYL52zVj_KGBMeymLNPJbHr9z9I6q8maxX9TNFiaC1DBBKisKN2DkLjhunlXDZ_fkzNcBg9PmufDkmCTC09fGHE4Pp8K4-8=s500-no?authuser=0][Here is the picture]]

* E#009 (04/05/2022) - discocup (A)
:PROPERTIES:
:CUSTOM_ID: orgbe249af
:END:
Just a modest old cup made of clay that has been set on top of a clay disc and is ready for the ancient human to use.

[[https://lh3.googleusercontent.com/pw/AM-JKLWMF7CqYsjoNws0b_cXcSUSfvxXxpNwJ9s2c-3czxbZxAlGV_daULTmrbIuzvQQdM4ceDlVN7Uvnvay7fBMzR3hFMt_gKCqarVQM0V5DQfSJ43OaHemQyi6L_TDs3_7e5D7xRb-0RKPDhgs38w1prM=s500-no?authuser=0][Here is the picture]]

* E#008 (24/04/2022) - stress explained (S)
:PROPERTIES:
:CUSTOM_ID: orgb8f21ea
:END:
This is an old piece of writing that I wrote many years ago. Why let it gather dust on the shelves?

I am not going to deny the fact that I have experienced stress. A LOT of it too. I have managed to tackle it well at times, and not so well at others. 

Before we dive in, we need to understand what does "stress" really mean. Psychologically, there are many definitions of stress. Stress could be defined as the body's reaction to an aversive stimulus which is found in the individual's external environment. Another definition is "Stress occurs when environmental demands exceed one's perception of the ability to cope" (Fink, 2016). A stimulus which causes stress is known as a stressor.

People use resources in order to cope with stress, and these resources vary from one individual to another. They range from the teddy bear you had since you were 6 years old, to the counselling sessions provided by your workplace.

Response to stress can be demonstrated in 4 different ways. These are as follows:
- cognitive
- physiological
- behavioural
- affective

Thomas Holmes and Richard Rahe have devised a way for us to use in order to measure our stress. This can be found [[https://horizonhealth.com/2019/06/13/whats-your-stress-load/][here]].

There are two types of stress: positive stress (eustress) and negative stress (distress). Distress is the one that is bad, the one that can cause anxiety and fear. Indeed, when experienced for a long period of time, negative stress can cause serious issues such as depression and physical illness. In 2017, an article was published outlining the impacts of stress on health, including but not limited to: cardiovascular disease, GI complications, endocrine disorders, and impaired immune system functions (Ranabir & Reetu, 2011; Yaribeygi, Panahi, Sahraei, Johnston, & Sahebkar, 2017).

Stress is not actually bad for you. Yes, you have read that right. The right amount of stress was the reason for why I made it to Medical school. For why I passed my exams. It shows that I care. However, have too much stress, and you will start experiencing all the bad aspects of it.

There are many ways to deal with this negative stress, and I think these are outlined nicely for you [[https://stress.lovetoknow.com/Positive_Strategies_in_Managing_Stress][here]]. My personal favourites are meditation and expressive writing. This is because they only take few minutes a day, and they do not require me to leave the house (especially useful if you live in a country where it rains most of the time).

Now moving on to the biology of stress. Back in the 1920s, an American physiologist called Walter Bradford Cannon performed experiments involving humans and animals. He saw that during stressful conditions, nerves and glands are triggered which cause the body to either fight, or flight. This is why he called this response as the "fight-or-flight response". The hypothalamus is the "stress centre" of all this action. It is called the "stress centre" because of its function during stress:

It causes the activation of the pituitary gland
It is responsible for the Autonomic Nervous System (ANS) control
The hypothalamus sends signals to the pituitary gland. The pituitary gland releases 2 important stress hormones. The first hormone is the ThyroTropic Hormone (TTH), this hormone causes the stimulation of the thyroid gland which, by releasing more hormones, provides further energy to the body. The second hormone is the Adrenal CorticoTropic Hormone (ACTH), this hormone stimulates the adrenal cortex (the outer part of the adrenal gland) which in turn produces hormones that release sugar from the liver into the bloodstream. This is known as Hypothalamic-Pituitary-Adrenocortical (HPA) Axis.

The ANS is the one that causes you to hyperventilate during stressful situations. It is also the one that causes your heart rate to increase. Furthermore, it redirects the blood flow from your digestive system to your muscles (digesting your last meal whilst being chased by a wolf is the last thing on your priority list). The ANS sends signals to your adrenal medulla (the inner part of the adrenal gland). This causes the adrenal glands to release 2 hormones, adrenaline (epinephrine) and noradrenaline (norepinephrine). These two have major functions in the body. For example, they cause the liver to produce more sugars (which boost your body's energy to either fight-or-flight). This is known as the Sympathetic-Adrenomedullary (SAM) Axis.

Shelley Taylor, a health psychologist, has suggested that the physiological processes outlined above may result in different response in females (Taylor, 2006). Along with her colleagues, she says that females experience a "tend-and-befriend response". They say that when stressed, females will protect their offspring (by tending to their needs) and will befriend the members of the surrounding environment, hence further minimising the offspring's vulnerabilities.

That is all! This is "stress" in a nutshell. I would like to write more, but the post would be too lengthy, and readers may get lost and bored. However, if you would like to learn more about stress, I have cited the sources which I have used in this post. You can use those as a starting point for further reading.

There are three main messages that I would like you to take away from all of this:
Not all stress is bad for you. Exam stress shows that you actually care about your studies. It shows that you want to succeed.
You should tackle the negative stress as soon as you encounter it. Utilise all the available resources which you have available. Try expressive writing and meditation, see how it goes. If they do not work, then move on to the next strategy. Keep doing so until you find the one that suits you the most.
Stress causes the release of MANY hormones and being exposed to stress for a prolonged period of time can actually cause many issues.

Take it easy and look after yourself.

_References_

Fink, G. (2016). Fink G. Stress, Definitions, Mechanisms, and Effects Outlined: Lessons from Anxiety. In: Fink G, ed. Stress: Concepts, Cognition, Emotion, and Behavior, Volume 1 of the Handbook of Stress Series. San Diego: Elsevier Inc., 2016: 3-11. In.

Ranabir, S., & Reetu, K. (2011). Stress and hormones. Indian journal of endocrinology and metabolism, 15(1), 18-22. doi:10.4103/2230-8210.77573

Taylor, S. E. (2006). Tend and Befriend: Biobehavioral Bases of Affiliation Under Stress. Current Directions in Psychological Science, 15(6), 273-277. doi:10.1111/j.1467-8721.2006.00451.x

Yaribeygi, H., Panahi, Y., Sahraei, H., Johnston, T. P., & Sahebkar, A. (2017). The impact of stress on body function: A review. EXCLI journal, 16, 1057-1072. doi:10.17179/excli2017-480

* E#007 (31/03/2022) - muddle the puddle-ator (A)
:PROPERTIES:
:CUSTOM_ID: org6736835
:END:
The sound-generating wheel. This is a remarkable wheel re-invention. It not only assists you in moving your vehicle in a CO2-free manner, but it also (through the use of friction and puddles) plays music for you to enjoy as you run your errands.

[[https://lh3.googleusercontent.com/pw/AM-JKLXzTNlf3H9UXzg2jjLKlrYKVshdDSGbpKIbAedOnAOMnLAMrr4g-kJ5r3Uf6yxKlWbvcLoJEYd9-xhoF1RlmcZrdHbbGkUl7cxt_Bz-f99nAaewK7i22rqfv2NnCOLs9IWSKb7rHzvfhIxOaV64eg=w720-h711-no?authuser=0][Here is the picture]]

* E#006 (30/03/2022) - a brat rat (A)
:PROPERTIES:
:CUSTOM_ID: org88d06eb
:END:
The brat rat. A rat that has become so scarce that it can no longer be found on a chessboard. It can only be seen by those who have mastered the game. Only those who have pondered about this topic a thousand times can perceive it for what it is. The rat is the only piece that may be swapped. The piece that can fool the enemy while also saving the comrades in the most unethical way possible.

[[https://lh3.googleusercontent.com/pw/AM-JKLW4ExSMpsQuv5h60pEQOGw9LEch6W_Echrua3UthUF9bVhn0HPhRNWrnLIBhKDyfkdW5Fq7L0JTrHbG9c_3cFDph01WmRoWP8OLJO4jma9OD8wWTyHWMm31SoVq53IhpaePMzPiW_DZAKpi1Vcpxg=w720-h714-no?authuser=0][Here is the picture]]

* E#005 (29/03/2022) - milk up the cup (A)
:PROPERTIES:
:CUSTOM_ID: orga5d427d
:END:
Whilst I was drawing this, my thinking was something along the lines of: drinketh from this cuppeth and thee shalt liveth forever, or peradventure thee shalt never see the ordinary again for thee wilt beest ascending to the metaverse.

[[https://lh3.googleusercontent.com/pw/AM-JKLVPriEhSE6C7JLG-PaNH65oJnyyFwanTfMIGOLfLVFCkE90jcvmKOCtxTk_KbHnDIkJWgbrE4_SbTsBfKBhx04EwmcjroOl9ATwy3zowe404bJQW6tEWdkuLCjZNB0rFI3fMz17e8qkkYBDuKET6Q=w670-h609-no?authuser=0][Here is the picture]]

* E#004 (28/03/2022) - school time with Albert Einstein (A)
:PROPERTIES:
:CUSTOM_ID: org196496e
:END:
Micky Mouse, on the other hand, has indeed attended Albert Einstein's Physics School (AEPS). He was a mischievous little guy, but a very imaginative one too. On the sand pit, he exuded vigour, wit, and hilarity. But during the lecture, he showed extreme hunger for knowledge and unfamiliarity...

[[https://lh3.googleusercontent.com/pw/AM-JKLU3elX3pVo78IeyEdfGTqzUcXzTqDiCg5YDh8eHZm_eUeNjcmyh1nqj7VaFXREycf63pd0yI7X8E61z9dQqFdCN6Na5urAjNnOPgcJdt4zTpLK8KlNQYMPF6vBuKZ4dyR63QI0dQ7iiVA3oOfnSog=w720-h721-no?authuser=0][Here is the picture]]

* E#003 (27/03/2022) - a kettle of metal (A)
:PROPERTIES:
:CUSTOM_ID: org8f5091c
:END:
Have you ever wished for a scrap metal kettle that could pour your morning coffee into a cup that was attached to it? No, me neither I. But consider this for a moment: would it be a fantastic invention? Or a violation of our [[https://hnvy.github.io/blog-1/00_journal/01_logs/journal_1_logs.html#org8d2b587][previous discussions]]?

[[https://lh3.googleusercontent.com/pw/AM-JKLVzTlhWV3gpt6GEMyB_cZfAgFZJCdv_843fhuLxNr3s-iAIHcqRlxKY2E4Dm1PIr55TMvtYVIXNb0y5NgvW-SqUaBXse9snnJ_PX4tXtjIz9T12hHQNdIUA-5g5CHRvMdvOL78ItARaDUPL-Z42Cg=w720-h697-no?authuser=0][Here is the picture]]

* E#002 (26/03/2022) - the last shroom heading to its doom (A)
:PROPERTIES:
:CUSTOM_ID: org9b31774
:END:
According to a legend, this is the final mushroom on the planet. And now it is being taken to the final door by a wanderer. The door that will determine whether it will be utilised as a simple ingredient in a potion to save the prince or whether it will be nurtured and grown. We'll never find out...

[[https://lh3.googleusercontent.com/pw/AM-JKLXqosMZ0Z1odemHmccMdPmGN_xsrGyKKi2iRDRLVew1PM8-BxijfZ8KLycK53tKjlDeOaJtlGt96Y9XkOHC2s9feRBdQVl0VvgNlVn8XrdFQs8cA7kaa4WGuxT9U-Cd4BVPEgN8HsCGHmUMuCdO7A=w720-h718-no?authuser=0][Here is the picture]]

* E#001 (25/03/2022) - fries, flies, and brain pies (A)
:PROPERTIES:
:CUSTOM_ID: org31b9d94
:END:
A blue alien is salivating because the platter in front of it - which contains three fries, a fly, and a brain pie - looks splendid. This is the first time I've ever used digital media to create a piece of art. It was quite a lot of fun.

[[https://lh3.googleusercontent.com/pw/AM-JKLXDlEkBjC4VBDeNRsyAC5B65dPs_gYgmjWEKBk1A-cjN437lRDerKnzhD069eon9Kh08uTnjCH6Tx2AnHm_7nZUbBvfUJ3n9l0Dz15dKugk_1EjZYlioV2sZeNlwZJEXpnoyv0A_ucIWwmYxmx84Q=w857-h782-no?authuser=0][Here is the picture]]
