#+TITLE: Journal 2 Logs

#+BEGIN_EXPORT html
<pre>
<code>> ./blog-1/00_journal/01_logs/journal_2_logs.html</code>
</pre>
#+END_EXPORT

[[https://hnvy.github.io/blog-1/][Home page]] - [[https://github.com/hnvy/blog-1/edit/main/src/00_journal/01_logs/journal_2_logs.org][ESotP]]

[[https://hnvy.github.io/blog-1/00_journal/01_logs/journal_1_logs.html][Previous part of log]] - [[https://hnvy.github.io/blog-1/00_journal/01_logs/journal_3_logs.html][Next part of log]]

-----

* Introduction
:PROPERTIES:
:CUSTOM_ID: intro
:END:
See [[https://hnvy.github.io/about.html#journal][this]].

* E#017 (02/11/2022) - go Google it (T)
:PROPERTIES:
:CUSTOM_ID: org1c1fe0f
:END:
[[file:./journal_1_logs.org::#org73993f1][Previously]], I have been a little too harsh on the medical students. I don't blame them, there is too much to learn and too little time. Their issues are exacerbated further by their variable clinical rotation experiences.

I have come to realise that the staff on the wards don't tell you to go and Google something because "they're lazy and don't want to teach", but rather, because some of them feel like you would not pay attention to the things that they were about to bestow upon yourself. Or, some may feel that they cannot teach things quite well, and hence avoid it altogether. And, that's a problem. This issue most probably originated when those specific staff members encountered some inattentive/uninterested students, and did what people are so good at: generalising.

As a result of the aforementioned issue, many staff members will suggest you to "just Google it." While that might be a good solution in a few situations, it actually isn't in many more. Just so you know, I'm not talking about the staff who are now too busy to teach you; rather, I'm talking about the ones who have some free time on their hands and would be willing to give you a lesson, yet they encourage you to Google it instead.

Sometimes, they may tell you to Google it because they are afraid of giving you the wrong information. I truly appreciate those people who admit that they don't know a certain topic.

Some, which I really appreciate, will advise you to go study the subject for a short while before returning to discuss it. Those staff are on a very different plane.

But why am I writing on this issue? You see, I think that teaching during the ward rounds/clinical rotations is paramount. The more varieties of explanations and analogies you hear of the same concept, the better. Why? Because it allows your brain to pick the ones it likes the most, and hence encode it in a way where you would understand and remember it better and for longer. Further, I imagine a piece of knowledge as a Rubik's Cube. You're very unlikely to solve a Rubik's Cube without having a look at all of the faces. The same thing applies to knowledge. Being a multifaceted entity, I think it would be far better to observe the same piece of information in different forms.

So, as a staff member, what can you do to ensure that students don't feel this way? Well, communication is key. Tell them! Inform them that you don't know enough about the subject to be able to provide much knowledge, but you are curious about what they would discover. If you're interested in teaching, let them know that you'd be pleased to teach them later in the day because you're a little busy right now. Give them a few minutes to learn about the subject before you bring it up for discussion. Inform them of a noteworthy clinical instance you recently encountered. Show a compelling blood test result to them. Show them a scan that is fascinating. Asking them to determine the diagnosis, investigation, and course of therapy of a clinical scenario (which you could discuss with them later that day).

It's critical to normalise forgetting rather than stigmatise it. If a student forgets something, don't insult them. This kind of behaviour against students is something I frequently see. The learner is unable to be familiar with every disease that exists, along with every investigation and treatment that has to be conducted. That is not conceivable for humans. The student has a plan, and they will carry it out. Therefore, just because they were unable to answer your question, it does not imply that they are a poor or inept student. No.

You might clarify the information before adding, "You need to know this as it is vital," rather than just saying, "You should know this," and leaving the conversation there. Compare the two earlier perspectives. Put yourself in the student's position. Which one do you like best?

Please allow me to remind you to remain humble. Never brag about how much you know or how much you can perform. Although it is great to know, the student is not some kind of recruiter, and thus they don't need to know. Instead of telling and expressing your passion for the field, bragging about your knowledge is counterproductive. I'd want to take this opportunity to remind you that, like the rest of us, you were once a novice. The journey of these students is just beginning, so showing off your knowledge won't do you any good...

Last but not least, refrain from mocking the pupil for providing a "silly answer." It's really challenging and stressful to respond to questions from staff, on the spot. The student wants you to believe that they are intelligent and deserving of your teaching. Killing off that admiration will hurt you more than it would help (for a start, they'll begin to do all in that is in their power to stay away from you, which fosters a toxic learning environment).

Empathise with the student; they are likely to have a lot going on.

How then, as a student, can you make sure that you benefit the most from ward teaching? You may think about a subject to discuss with the staff and then see where things go from there. Or, you can hint at the above suggestions. What if that doesn't succeed, though? I'll let you know when I learn the answer to this question...

* E#016 (16/10/2022) - following a plan (T)
:PROPERTIES:
:CUSTOM_ID: org29jro21
:END:
Recently, I have been slacking on my work. I open the computer, launch my usual work-related software, and then, once I think of something trivial such as "how to match the capturing group in the replace box using RegEx" go down a rabbit whole which takes 3-4 hours.

It is getting hideous, and frankly, I have had enough.

What follows is a public mini-reflection which utilises what I have spoken about [[file:./00_journal/01_logs/journal_1_logs.org#org8d2b587][previously]]:

#+BEGIN_QUOTE
I need to complete this chapter. No, I want to complete this chapter. I have wasted too much time on trivial things that are not as useful as the chapter I am currently learning. Sure, learning how to match the capturing group in RegEx is cool, but is it useful *right now*? No.

The medical chapter I am referring to is fascinating. It is beautiful. Som much pathophysiology and so much content to learn about. So many new pieces of life-saving information that many before me have memorised and learned off by heart.

Memorisation is not the problem. I don't what is. My learn drive seems to, uselessly, want me to search up how to match the capturing group in RegEx rather than how to attempt to diagnose pneumonia using clinical judgement.

So, from now on, I will use [[https://github.com/hnvy/day-ploy][day-ploy]] to fix this. I want to have a fixed routine where I don't waste time on things which do not benefit me right now.

Sure, this seems like a radical approach to some, but it isn't. I have stalled for too long. Although the chapter is quite lengthy, I shouldn't unjustifiably be afraid of it and put off acquiring what knowledge it can bestow upon me.
#+END_QUOTE

Now that I got that off my chest, I should probably go back to work.

Side note: use ~$0~ or ~${0}~ to match the capturing group in the replace box in RegEx. See [[https://www.regular-expressions.info/replacebackref.html][this]] for more detail.
