#+TITLE: ./blog-1

#+BEGIN_EXPORT html
<pre>
<code>> ./blog-1/index.html</code>
</pre>
#+END_EXPORT

[[https://hnvy.github.io/][Main directory]] - [[https://github.com/hnvy/blog-1/edit/main/src/index.org][ESotP]]

-----

* Files
:PROPERTIES:
:CUSTOM_ID: files
:END:
- 00_journal
  - 01_logs
    - [[file:./00_journal/01_logs/journal_1_logs.html][journal_1_logs.org]]
    - [[file:./00_journal/01_logs/journal_2_logs.html][journal_2_logs.org]]
- 01_software
  - 00_misc
    - 01_logs
      - [[file:./01_software/00_misc/01_logs/misc_1_logs.html][misc_1_logs.org]]
  - 01_editors
    - 01_logs
      - [[file:./01_software/01_editors/01_logs/editors_1_logs.html][editors_1_logs.org]]
    - 02_pearls
      - [[file:./01_software/01_editors/02_pearls/editors_1_pearls.html][editors_1_pearls.org]]
  - 02_coding
    - 01_logs
      - [[file:./01_software/02_coding/01_logs/coding_1_logs.html][coding_1_logs.org]]
- 02_science
  - 01_logs
    - [[file:./02_science/01_logs/science_1_logs.html][science_1_logs.org]]
- 03_language
  - 01_logs
    - [[file:./03_language/01_logs/language_1_logs.html][language_1_logs.org]]

* Archive
:PROPERTIES:
:CUSTOM_ID: archive
:END:
You can find the archive for all the subdomains [[https://hnvy.github.io/archive.html][here]].

#+BEGIN_EXPORT html
<p>
<hr style="width:75%;">
</p>

<footer style="font-size: 0.75em; font-style: italic; text-align: center; margin-left: auto; margin-right: auto;">
<p>Unless otherwise noted, every original piece of writing, artwork, and code snippet on <a href="https://hnvy.github.io/">this site</a> is licensed under <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPLv3+</a>.</p>

<p>Please note that the content on this site is NOT intended to be used as a diagnostic or treatment tool. If you are having any symptoms, you should always seek professional medical attention. My notes are NOT intended to be medical advice; you should seek guidance from your physician rather than the internet. Once again, this document is NOT for medical advice! In fact, NONE of this site's information should be taken as advice, because the content on this site may NOT be applicable to you.</p>

<p>Ok, I think that should be enough...</p>
</footer>
#+END_EXPORT
